### ISSUE TITLE
Question Event Resize

### ISSUE THREAD

**Issue by boukenka** [majorimi/blazor-components#49]
Hello,

Is there an effective way to get the event when the browser window is resized or a control is resized ? 
With no real lag ? Often I have found solutions with a listener with a frequency for the check.
Maybe with Resize Observer https://drafts.csswg.org/resize-observer-1/ or resize event https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event ? Could be nice to have this feature in your 'blazor-components' project.

Thanks for any answer. 😄

**Comment by majorimi** [comment]
Hi @boukenka, 

Yes definitely ways to get nonfictions about "resize". However it requires JS interop to happen. Which definitely will have impact on performance. Cannot really tell you the exact delay (lag) time. Since Blazor is a client side framework. So the performance can be hugely impacted by the client machine performance.

I **already have some "Global" events listener wired up to Blazor via JS interop**. You can check e.g. [Mouse events in this demo app](https://blazorextensions.z6.web.core.windows.net/jsinterop#mouse-js). Please have a look on it and let me know if you think it has the required performance. If yes then I can add very similar API interfaces for other global events like you requested: resizing.

**Comment by boukenka** [comment]
Thanks @majorimi. I had a look to the demo. It seems pretty fast. It should have the required performance.

**Comment by majorimi** [comment]
Yes it is pretty fast. Even with the UI rendered and log scrolling to the bottom (that is another JS call)...
Ok I will add "Resize" events support for Window and HTML elements. Probably will be in the next release.

**Comment by boukenka** [comment]
Thanks @majorimi  and have a nice week-end!

**Comment by majorimi** [comment]
@boukenka I have merged Resize-Js to the next release branch. Finalizing on small component so in a few days I will publish v1.1.0 Nuget packages.

**Comment by majorimi** [comment]
Hi @boukenka,

I'm closing your request as it was deployed with v1.1.0. You can download latest [Nuget package](https://www.nuget.org/packages/Majorsoft.Blazor.Components.Common.JsInterop/). See usage and try out in [Demo app Resize-JS](https://blazorextensions.z6.web.core.windows.net/jsinterop#resize-js).

Hope you will be satisfied with the lag time as well.

**Comment by boukenka** [comment]
@majorimi Sorry it took some time to answer you. I did some tests this morning. The solution you have implemented is really good. The lag time is very small. Thank you again 😄

**Comment by majorimi** [comment]
Hi @boukenka,

Good to hear that 😄 Please check usage example which is currently missing DisposeAsync() call. Since all JSInterop should be disposed. However I made some mistake in that so currently you will get Exception. I already fixed that which will be published soon in v1.2.

Also note that v1.2 will have a small breaking change. All namespaces renames must be @using Majorsoft.Blazor.* So it is simple to fix....

**Comment by majorimi** [comment]
Ok v1.2.0 was released today with your request in it...

**Comment by boukenka** [comment]
Hi  @majorimi 

I have updated my project with the latest version v1.2.0 (also based on the demo code). 
It works perfectly. Thanks again.
