### ISSUE TITLE
GDPR Component (Blazor Server) - Unhandled exception on page reload

### ISSUE THREAD

**Issue by Paul-Schroeder** [majorimi/blazor-components#88]
Using Blazor **SERVER**, reloading the page while using the GdprBanner component triggers an unhandled exception (below).  This occurs even when the component is defined only once in MainLayout.razor.  I think it may have to do with use of a static bool for the `Initialized` variable in GdprBanner.razor.

See: [Blazor server-side and static fields](https://github.com/dotnet/aspnetcore/issues/15451)

"Since the server is a single process, static field values are shared between all sessions. There are no app-domains in .NET core to isolate values between sessions. This behavior is inconsistent with client-side Blazor, where static fields behave like one might assume, one value per client application/session."

In other words, reloading the page is likely not disposing/resetting the static Initialized variable to false, yet it should not trigger an exception.  Users reloading a page is a relatively common scenario.

**Error:**
ApplicationException: Component: 'GdprBanner' is not allowed to have multiple instances. Please define it one your e.g.: 'MainLayout.razor' or some common place.
Majorsoft.Blazor.Components.GdprConsent.GdprBanner.OnInitialized()
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(ref DiffContext diffContext, int frameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(ref DiffContext diffContext, int frameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(ref DiffContext diffContext, int newFrameIndex)

![GdprBanner ApplicationException](https://user-images.githubusercontent.com/3439556/129252197-4883e797-9e9d-4a28-b632-f9b34b68f928.png)

**Comment by majorimi** [comment]
Hi @Paul-Schroeder,
Thanks for reporting this issue. Yes now I was able to replicate it. Actually the code is resetting `Initialized` value. But the problem is `Dispose` method runs after the second instance is Initialized... So actually every 2nd refresh works good (which is still not great).
Just started applying this technique for a few initializer component. But it seems I have rethink it.

Here is the dispose code but does not run "in time":
```
public void Dispose()
{
    Initialized = false;
}
```

**Comment by Paul-Schroeder** [comment]
It might be a pain, but I believe JavaScript's beforeunload event gets fired on a page refresh. Tying into that event could provide another path for setting `Initialized = false;`.  That event gets fired when the window, the document and its resources are about to be unloaded (i.e. WindowEventHandlers.onbeforeunload).

Link to [WindowEventHandlers.onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload)

"Other than the issue with the debugger statement, the handlers are executed whether you are reloading or closing the tab."
[StackOverflow issue trying to use debugger with page reload](https://stackoverflow.com/questions/50705759/beforeunload-event-does-not-fire-after-page-refresh-chrome)

**Comment by majorimi** [comment]
Yes I had an idea yesterday evening. To use `Scoped` services. Because should do what I need:
- WASM: it acts as Singleton which is like `static` and good for client side app
- Server side: it behaves normally, so per request will inject a new instance.

Still doing some testing. But so far looks good. If you want you can pull down the `release/1.5.0` branch and try it out.
**Currently cannot tell you when I will be publish new Nuget packages. Trying to finish some docs and one more components for Tooltips. Hope v1.5 will be released end of August**. You can check the project or ping me.
Thanks.

**Comment by Paul-Schroeder** [comment]
Any suggestions on how best to build/test this for you? I pulled the 1.5 branch, updated the GdprConsent project's NuGet package version, then rebuilt/re-referenced the package using the new version.  That gives me the error, "The type or namespace name '_Toggle_' does not exist in the namespace 'Majorsoft.Blazor.Components' (are you missing an assembly reference?)" (The same error is generated for other dependencies like Modal, Common.JsInterop.Focus, and CssEvents).

I believe this is because in the source they are **project references** and not NuGet package references. I do see there are some azure pipeline Yaml files in the solution, but I don't see anything in the contribution guidelines on manual build/testing using NuGet packages here: [Information and Guidelines for Contributors](https://github.com/majorimi/blazor-components/blob/master/CONTRIBUTING.md)

I could probably test it using the Majorsoft.Blazor.Components.TestApp project, but I was thinking that building a new NuGet package for the GdprConsent component and trying to use it in my own solution would be a better test.  Please let me know if you have a suggestion on how to build that NuGet package and also bring along the dependency project/packages; clearly I should be using a different procedure here.

Screenshot of error after referencing the Majorsoft.Blazor.Components.GdprConsent NuGet package built from the v1.5 branch:
![GdprConsent NuGet Reference Errors](https://user-images.githubusercontent.com/3439556/129386610-26e55d68-d853-4eb0-8510-dfcb4624dc16.png)

**Comment by majorimi** [comment]
Hmm I might misunderstood you but I think you are doing it wrong... So if I'm not mistaken you are trying to create new Nuget.org packages and use it. But you cannot access my Account on Nuget.org and cannot publish new packages under my name. That would be super bad if everyone could publish any packages for everyone. In that case I would just override all Microsoft or ANY Nuget packages with bugs or malicious codes...

**So please do not change (increase) Nuget versions because they won't exists on Nuget.org until I upload it. So probably that is why you have build errors.** But correct me if I'm wrong.

Yes I have build checks. So a CI pipeline runs on every commit (Push to Github might be with many commits). And branch `release/1.5.0` was running perfectly yesterday.
Also Nuget packages generated with another Pipeline which has package version parameter. It is updating Versions automatically. New Nuget packages then pushed to a private Nuget Antifactory from where I publish with my Nuget.org Key.

Here is a detailed explanation of the [project structure](https://github.com/majorimi/blazor-components/blob/master/CONTRIBUTING.md#project-structure). Where you can check how to run the project locally. 
But a short explanation why not using Nugets locally is: **because the development cycle would be horribile, like half an hour per any change**!
Even a single character change would require all components to Nuget packaged and uploaded to Nuget.org. Demo application updated with new Versions and then can teste the change. If result is still not good then next change, next cycle... package... upload... update.... test... -> and again -> and again.... Super bad 👎 
It is much better to locally reference all components directly (with Project reference) and any change will be impact the local test apps immediately. With `dotnet watch run` application will reload as well. Development cycle is 30 sec (or less) not 30 MINS! 👍 

**So you should reset every changes what you made.** And just **run any of the provided applications in the `TestApps`.** Even `run.bat` files are provided just execute it. 
If you want to **check the new code in your project then just Project reference it, for now**. As mentioned currently trying to finish one more component and **will publish fixes and new components to Nuget.org at the end of August**.

Let me know how it went. Thanks.

**Comment by Paul-Schroeder** [comment]
Apologies for following up, initially, I got distracted and am just now getting back to this project.  In any case, no worries, I am happy to wait until the next publish of the 'official' NuGet packages.  In the meantime, tonight, I was able to confirm the changes in the release/1.5.0 branch appear to have fixed this issue.

Per your thought: 
- _>> So if I'm not mistaken you are trying to create new Nuget.org packages and use it._ 

No, not at all...I created a local NuGet package and referenced that using a local package source.  You are correct that this approach is an inefficient testing practice.  My understanding was that you had already fixed/tested it using the test project and I just wanted to verify that fix worked in a "live" scenario.

On the second go-around, I did try uninstalling the 1.4.0 NuGet package and tried to use project references.  However, this approach caused Visual Studio 2019 v16.10.4 to throw compile errors.  In addition, Visual Studio was giving me yellow triangles  and acting like there was something wrong (see images):
![GdprBanner Package Reference Issues](https://user-images.githubusercontent.com/3439556/129825804-c8309258-da62-4483-b5c8-98dc347a65e9.png)

![GdprConsent NuGet Reference Errors](https://user-images.githubusercontent.com/3439556/129825819-7fae0c50-5888-40e3-98ab-a0d6a10a0a1a.png)

Between then and today, the only thing that changed in my system was both a shutdown of Visual Studio and a reboot of the computer.  However, when I retried this experiment tonight, there were no build errors for some reason.  As such, I was able to confirm your fix for this one seems to work - very nice!
